@startuml

class Solution41{
    ' Methods
    +{static}main(String)
}

class NameSorter{
    'Variables
    -listNames: ArrayList<String>

    'Methods
    'Adds elements to output string
    +createOutput(): String output
    'Sorts arraylist in alphabetical order
    -sortList()
}

class MyFileReader{
    'Variables
    -listNames: ArrayList<String> list

    'Adds elements to listNames from input file
    +scanInputFile(File inputFileName): ArrayList<String> list
}

class MyFileWriter{
    'Writes string to output file
    +writeToFile(String output)
}



Solution41--NameSorter
@enduml